---
- name: Deploy HDP 2.2
  hosts: all
  sudo: true
  tasks:
  - name: Install latest Java
    yum: name=java state=latest

  - name: Install latest wget
    yum: name=wget state=latest

  - name: Install ntp daemon
    yum: name=ntp state=latest

  - name: Update OpenSSL
    yum: name=openssl state=latest

  - name: Run configuration script
    script: init_hdp.sh

  - name: Install epel repo
    yum: name=epel-release state=latest

  - name: Install python pip
    yum: name=python-pip state=latest

  - name: Install Python requests module
    pip: name=requests

  - name: Install vim
    yum: name=vim state=latest

  - name: Ensure Ambari server running
    service: name=ambari-server state=restarted
    register: ambari_start

  - name: Run Ambari host registration script
    script: blueprint.py
